### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by legoktm** [FTB-Gamepedia/mediawiki-rs#6]
Hi, could you indicate what license this code is released under? See https://choosealicense.com/

**Comment by legoktm** [comment]
@retep998 is this something you could shed some light on?

**Comment by eric-unc** [comment]
This library is pretty specific to certain tools used by the FTB Wiki; I wouldn't recommend using it. It doesn't even have an edit function. Retep has talked about expanding before but if you want a tool for MW in Rust, there are other things out there, or you could start from scratch. He probably wouldn't care if you used this for something though.

**Comment by retep998** [comment]
Oh right, I should add a license.

**Comment by legoktm** [comment]
@eric-unc unfortunately, I haven't taken a real look at the code yet (outside of trying to find a license statement) because it has no license, because I am working on Rust things for MediaWiki and don't want to inadvertently copy something that I can't use...

**Comment by legoktm** [comment]
Thank you!
